import type { MealCandidate } from "./types.js";

export const curatedMealCatalog: MealCandidate[] = [
  {
    key: "curated:pho-ga",
    source: "curated",
    name: "Phở gà",
    description: "Món nước ấm, dễ ăn, có thể điều chỉnh lượng bánh phở theo mục tiêu calo.",
    calories: 430,
    protein: 30,
    carbs: 52,
    fat: 10,
    ingredients: ["bánh phở", "ức gà", "nước dùng", "hành", "rau thơm"],
    steps: ["Nấu nước dùng", "Luộc và xé gà", "Trụng bánh phở", "Cho gà và nước dùng vào tô"],
    tags: ["món nước", "ấm", "giàu protein", "việt nam"],
    diets: ["flexible"],
    goals: ["balanced", "high_protein"],
    mealPeriods: ["breakfast", "lunch", "dinner"],
    weatherTags: ["cold", "rainy", "neutral"],
    cuisine: "vietnamese",
    cookingMinutes: 45,
    budget: "medium"
  },
  {
    key: "curated:goi-cuon-tom",
    source: "curated",
    name: "Gỏi cuốn tôm",
    description: "Bữa nhẹ nhiều rau, phù hợp ngày nóng và có thể tăng tôm để bổ sung protein.",
    calories: 360,
    protein: 24,
    carbs: 44,
    fat: 9,
    ingredients: ["tôm", "bánh tráng", "bún", "xà lách", "rau thơm"],
    steps: ["Luộc tôm", "Chuẩn bị rau và bún", "Làm mềm bánh tráng", "Cuốn các nguyên liệu"],
    tags: ["món nhẹ", "nhiều rau", "mát", "việt nam"],
    diets: ["flexible"],
    goals: ["balanced", "low_calorie", "high_protein"],
    mealPeriods: ["lunch", "dinner"],
    weatherTags: ["hot", "neutral"],
    cuisine: "vietnamese",
    cookingMinutes: 25,
    budget: "medium"
  },
  {
    key: "curated:com-ga-rau",
    source: "curated",
    name: "Cơm gà áp chảo và rau",
    description: "Bữa chính cân bằng, giàu protein và dễ điều chỉnh khẩu phần cơm.",
    calories: 520,
    protein: 38,
    carbs: 58,
    fat: 14,
    ingredients: ["cơm", "ức gà", "rau củ", "dầu ăn", "gia vị"],
    steps: ["Ướp gà", "Áp chảo gà", "Luộc hoặc xào rau", "Ăn kèm cơm"],
    tags: ["cân bằng", "giàu protein", "cơm", "việt nam"],
    diets: ["flexible"],
    goals: ["balanced", "high_protein"],
    mealPeriods: ["lunch", "dinner"],
    weatherTags: ["neutral", "hot", "cold"],
    cuisine: "vietnamese",
    cookingMinutes: 30,
    budget: "medium"
  },
  {
    key: "curated:bun-dau-hu",
    source: "curated",
    name: "Bún đậu hũ rau củ",
    description: "Lựa chọn không thịt, có đậu hũ làm nguồn protein và nhiều rau tươi.",
    calories: 440,
    protein: 22,
    carbs: 58,
    fat: 13,
    ingredients: ["bún", "đậu hũ", "dưa leo", "rau thơm", "nước tương"],
    steps: ["Áp chảo đậu hũ", "Chuẩn bị bún và rau", "Pha nước tương", "Bày ra đĩa"],
    tags: ["ăn chay", "đậu hũ", "nhiều rau", "việt nam"],
    diets: ["flexible", "vegetarian", "vegan"],
    goals: ["balanced", "low_calorie"],
    mealPeriods: ["lunch", "dinner"],
    weatherTags: ["hot", "neutral"],
    cuisine: "vietnamese",
    cookingMinutes: 25,
    budget: "low"
  },
  {
    key: "curated:chao-yen-mach-trung",
    source: "curated",
    name: "Cháo yến mạch trứng",
    description: "Bữa sáng ấm, nhanh, dễ tiêu và có thể thêm rau hoặc thịt nạc.",
    calories: 350,
    protein: 20,
    carbs: 40,
    fat: 12,
    ingredients: ["yến mạch", "trứng", "nước dùng", "hành", "tiêu"],
    steps: ["Nấu yến mạch với nước dùng", "Cho trứng vào khuấy", "Nêm gia vị", "Thêm hành"],
    tags: ["bữa sáng", "ấm", "nhanh", "ít calo"],
    diets: ["flexible", "vegetarian"],
    goals: ["balanced", "low_calorie"],
    mealPeriods: ["breakfast", "late_night"],
    weatherTags: ["cold", "rainy", "neutral"],
    cuisine: "vietnamese",
    cookingMinutes: 15,
    budget: "low"
  },
  {
    key: "curated:salad-ga",
    source: "curated",
    name: "Salad gà trứng",
    description: "Bữa nhẹ giàu protein, phù hợp khi muốn kiểm soát calo trong ngày nóng.",
    calories: 390,
    protein: 35,
    carbs: 20,
    fat: 18,
    ingredients: ["ức gà", "trứng", "xà lách", "cà chua", "dưa leo"],
    steps: ["Áp chảo gà", "Luộc trứng", "Cắt rau", "Trộn với lượng sốt vừa phải"],
    tags: ["salad", "giàu protein", "ít calo", "mát"],
    diets: ["flexible", "keto"],
    goals: ["low_calorie", "high_protein"],
    mealPeriods: ["lunch", "dinner"],
    weatherTags: ["hot", "neutral"],
    cuisine: "international",
    cookingMinutes: 25,
    budget: "medium"
  },
  {
    key: "curated:bo-xao-bong-cai",
    source: "curated",
    name: "Bò xào bông cải",
    description: "Món giàu protein, ít tinh bột và phù hợp với bữa tối nhanh.",
    calories: 460,
    protein: 36,
    carbs: 18,
    fat: 26,
    ingredients: ["thịt bò", "bông cải", "tỏi", "dầu ăn", "gia vị"],
    steps: ["Ướp bò", "Xào nhanh thịt bò", "Xào bông cải", "Trộn và nêm lại"],
    tags: ["giàu protein", "ít tinh bột", "keto", "nhanh"],
    diets: ["flexible", "keto"],
    goals: ["high_protein", "balanced"],
    mealPeriods: ["lunch", "dinner"],
    weatherTags: ["neutral", "cold", "rainy"],
    cuisine: "vietnamese",
    cookingMinutes: 25,
    budget: "medium"
  },
  {
    key: "curated:canh-chua-ca",
    source: "curated",
    name: "Canh chua cá ăn cùng cơm",
    description: "Món có vị thanh, nhiều rau và dễ ăn trong thời tiết nóng.",
    calories: 500,
    protein: 32,
    carbs: 62,
    fat: 12,
    ingredients: ["cá", "cà chua", "dứa", "đậu bắp", "cơm"],
    steps: ["Nấu nước canh", "Cho cá vào", "Thêm rau và gia vị chua", "Ăn cùng cơm"],
    tags: ["món nước", "thanh", "nhiều rau", "việt nam"],
    diets: ["flexible"],
    goals: ["balanced", "high_protein"],
    mealPeriods: ["lunch", "dinner"],
    weatherTags: ["hot", "neutral"],
    cuisine: "vietnamese",
    cookingMinutes: 35,
    budget: "medium"
  }
];
